name: Deploy to Firebase Prod

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy to Firebase Prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash
      - name: Find Function Directories
        id: find-dirs
        run: echo "::set-output name=dirs::$(find . -type d -name 'functions')"
      - name: Deploy Functions
        run: |
          for dir in ${{ steps.find-dirs.outputs.dirs }}; do
            echo "Installing dependencies in directory $dir"
            npm install --prefix $dir
            echo "Deploying functions in directory $dir"
            cd $dir
            echo $FIREBASE_ADMIN_KEY >> ./service-account.json
            mkdir -p assets
            mv ./service-account.json assets/
            firebase functions:config:set \
            app.credentials_file_name="credentials" \
            app.email_username="${{ secrets.EMAIL_USERNAME }}" \
            app.email_password="${{ secrets.EMAIL_PASSWORD }}" \
            app.email_host="${{ secrets.EMAIL_HOST }}" \
            app.email_from="${{ secrets.EMAIL_FROM }}" \
            app.base_url="$BASE_URL" \
            --project ${{ secrets.PROJECT_ID }} \
            --token "${{ secrets.FIREBASE_TOKEN }}"
            firebase deploy --only functions:config --project ${{ secrets.PROJECT_ID }} --token "${{ secrets.FIREBASE_TOKEN }}"
            firebase deploy --only functions --project ${{ secrets.PROJECT_ID }} --token "${{ secrets.FIREBASE_TOKEN }}"
          done
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_ADMIN_KEY: ${{secrets.SA_JSON_FILE}}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
